version: '3.8'

services:
  robot_navigator:
    build: .
    image: robot_navigator:latest
    container_name: robot_navigator
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/root/ros2_ws/src/robot_navigator
    network_mode: host
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /root/ros2_ws/install/setup.bash &&
               ros2 launch robot_navigator obstacle_avoidance.launch.py"
